apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-web-app
  template:
    metadata:
      labels:
        app: flask-web-app
    spec:
      containers:
      - name: flask-container
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/flask-docker-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: AWS_SECRET_ACCESS_KEY
