apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops-container
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/mlops-project-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MONGODB_URL
