apiVersion: v1
kind: Service
metadata:
  name: flask-image-service
  labels:
    app: flask-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-web-app
